image: node:latest

variables:
  APP_ID: lts-cms-base

stages:
  - build
  - deploy

cache:
  paths:
    - frontend/node_modules/

before_script:
  - npm --prefix frontend install

build_frontend:
  stage: build
  script:
    - npm run build:production
  artifacts:
    paths:
      - frontend/public

deploy_to_heroku:
  stage: deploy
  before_script:
    - npm install -g heroku
    - heroku create $APP_ID --manifest
  script:
    - git subtree push --prefix backend heroku master


deploy_to_netlify:
  stage: deploy
  dependencies:
    - build_frontend
  before_script:
    - npm install netlify-cli -g
    - sed -i s/__APP_ID__/${APP_ID}/g netlify.toml
    # TODO: Set netlify site name to app-id
    # - export NETLIFY_APP_DATA=$(printf '\{ "site_id" : "%s", "name" : "%s" \}' $NETLIFY_SITE_ID $APP_ID)
    # - netlify api updateSite --data $NETLIFY_APP_DATA
  script:
    - netlify --telemetry-disable
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
