image: node:latest

variables:
  APP_ID: lts-cms-core
  PG_PLAN: hobby-dev

stages:
  - build
  - deploy

cache:
  paths:
    - frontend/node_modules/

before_script:
  - npm --prefix frontend install

build_frontend:
  stage: build
  script:
    - sed -i s/__APP_ID__/${APP_ID}/g frontend/.env-cmdrc.json
    - npm --prefix frontend run build
  artifacts:
    paths:
      - frontend/public

deploy_to_heroku:
  stage: deploy

  before_script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$APP_ID.git
    - npm install -g heroku
    - heroku create $APP_ID || echo 'App already exist, skipping app creation...'
    - heroku addons:create heroku-postgresql:$PG_PLAN --app $APP_ID --name PG_$APP_ID --wait || echo 'DB already exist, skipping creation...'

  script:
    - git subtree --prefix backend push heroku master


deploy_to_netlify:
  stage: deploy
  
  before_script:
    - npm install netlify-cli -g
    - netlify --telemetry-disable
  script:
    - netlify deploy --dir frontend --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
