image: node:latest

variables:
  APP_ID: lts-cms-core
  PG_PLAN: hobby-dev

stages:
  - build
  - deploy

cache:
  paths:
    - frontend/node_modules/

before_script:
  - npm --prefix frontend install

build_frontend:
  stage: build
  script:
    - sed -i s/__APP_ID__/${APP_ID}/g frontend/.env-cmdrc.json
    - npm run build:production
  artifacts:
    paths:
      - frontend/public

deploy_to_heroku:
  stage: deploy

  before_script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$APP_ID.git
    - npm install -g heroku
    - heroku create $APP_ID || echo 'App already exist, skipping app creation...'
    - heroku addons:create heroku-postgresql:$PG_PLAN || echo 'DB already exist, skipping creation...'
  
  script:
    - git subtree --prefix backend push heroku master


deploy_to_netlify:
  stage: deploy
  
  dependencies:
    - build_frontend
  
  before_script:
    - npm install netlify-cli -g
    - > 
        netlify api getSite --data \ 
        $(printf '{ "site_id": "%s", "site_name": "%s" }' "$NETLIFY_SITE_ID" "$APP_ID")
  
  script:
    - netlify --telemetry-disable
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
