image: node:latest

variables:
  APP_ID: lts-cms-core
  PG_PLAN: hobby-dev

stages:
  - build
  - publish

cache:
  paths:
    - frontend/node_modules/
    - backend/node_modules/

build_frontend_app:
  stage: build
  before_script:
    - npm --prefix frontend install
  script:
    - sed -i s/__APP_ID__/${APP_ID}/g frontend/.env-cmdrc.json
    - npm --prefix frontend run build
  artifacts:
    paths:
      - frontend/public

build_backend_admin:
  stage: build
  variables:
    NODE_ENV: production
  before_script:
    - npm install -g strapi@alpha
    - npm --prefix backend install
  script:
    - npm --prefix backend run build
  artifacts:
    paths:
      - backend/build

deploy_to_heroku:
  stage: publish

  before_script:
    - npm install -g heroku
    - heroku create $APP_ID || echo 'App already exist, skipping app creation...'
    - heroku addons:create heroku-postgresql:$PG_PLAN --app $APP_ID --name lts-pg-$APP_ID --wait || echo 'DB already exist, skipping creation...'
    - heroku config:set APP_ID=$APP_ID --app $APP_ID 
    - git checkout master
    - git fetch --unshallow
  script:
    - git add -f backend/build
    - git commit -m "Attaching pre-compiled Admin UI to Heroku build"
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$APP_ID.git
    - git push -f heroku HEAD:master

deploy_to_netlify:
  stage: publish
  
  before_script:
    - npm install netlify-cli -g
    - netlify --telemetry-disable
  script:
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
