version: '3'

services: 
  frontend:
    working_dir: /app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      GATSBY_WEBPACK_PUBLICPATH: /
      STRAPI_URI: backend:1337